### ISSUE TITLE
NoMethodError: undefined method `[]' for nil

### ISSUE THREAD

**Issue by n-rodriguez** [trailblazer/trailblazer-activity#60]
Hi there!

I've got this error when running my app in production :

```sh
NoMethodError: undefined method `[]' for nil (NoMethodError)

        outputs[signal]
               ^^^^^^^^
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/circuit.rb:80:in `next_for'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/circuit.rb:54:in `block in call'
  from <internal:kernel>:187:in `loop'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/circuit.rb:44:in `call'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity.rb:13:in `call'
  from trailblazer-activity-dsl-linear (1.2.5) lib/trailblazer/activity/dsl/linear/strategy.rb:105:in `call'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/task_wrap/call_task.rb:13:in `call_task'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `call'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `block in call'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `each'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/task_wrap/pipeline.rb:16:in `call'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/task_wrap/runner.rb:23:in `call'
  from trailblazer-activity (0.16.2) lib/trailblazer/activity/task_wrap.rb:28:in `invoke'
  from trailblazer-endpoint (827ac62bdb4c) lib/trailblazer/endpoint/options.rb:37:in `options_for'
  from trailblazer-endpoint (827ac62bdb4c) lib/trailblazer/endpoint/controller.rb:133:in `endpoint_for'
  from trailblazer-endpoint (827ac62bdb4c) lib/trailblazer/endpoint/controller.rb:140:in `endpoint'
  from vendor/engines/concerto_espagne/app/controllers/concerto_espagne/pages_controller.rb:12:in `home'
  from trailblazer-endpoint (827ac62bdb4c) lib/trailblazer/endpoint/controller.rb:63:in `send_action'
  from actionpack (7.1.3.2) lib/abstract_controller/base.rb:224:in `process_action'
  from actionpack (7.1.3.2) lib/action_controller/metal/rendering.rb:165:in `process_action'
  from actionpack (7.1.3.2) lib/abstract_controller/callbacks.rb:259:in `block in process_action'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  from route_translator (5b62e421c349) lib/route_translator/core_ext/controller_patch.rb:30:in `set_locale_from_params'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
  from activesupport (7.1.3.2) lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
  from app/controllers/concerns/base_controller/settings/time_zone.rb:20:in `set_time_zone'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
  from turbo-rails (2.0.5) lib/turbo-rails.rb:24:in `with_request_id'
  from turbo-rails (2.0.5) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
  from sentry-rails (5.17.3) lib/sentry/rails/controller_transaction.rb:17:in `block in sentry_around_action'
  from sentry-ruby (5.17.3) lib/sentry/hub.rb:109:in `block in with_child_span'
  from sentry-ruby (5.17.3) lib/sentry/span.rb:211:in `with_child_span'
  from sentry-ruby (5.17.3) lib/sentry/hub.rb:107:in `with_child_span'
  from sentry-ruby (5.17.3) lib/sentry-ruby.rb:490:in `with_child_span'
  from sentry-rails (5.17.3) lib/sentry/rails/controller_transaction.rb:14:in `sentry_around_action'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:141:in `run_callbacks'
  from actionpack (7.1.3.2) lib/abstract_controller/callbacks.rb:258:in `process_action'
  from actionpack (7.1.3.2) lib/action_controller/metal/rescue.rb:25:in `process_action'
  from actionpack (7.1.3.2) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
  from activesupport (7.1.3.2) lib/active_support/notifications.rb:206:in `block in instrument'
  from activesupport (7.1.3.2) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
  from sentry-rails (5.17.3) lib/sentry/rails/tracing.rb:54:in `instrument'
  from activesupport (7.1.3.2) lib/active_support/notifications.rb:206:in `instrument'
  from actionpack (7.1.3.2) lib/action_controller/metal/instrumentation.rb:73:in `process_action'
  from actionpack (7.1.3.2) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
  from activerecord (7.1.3.2) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
  from actionpack (7.1.3.2) lib/abstract_controller/base.rb:160:in `process'
  from actionview (7.1.3.2) lib/action_view/rendering.rb:40:in `process'
  from actionpack (7.1.3.2) lib/action_controller/metal.rb:227:in `dispatch'
  from actionpack (7.1.3.2) lib/action_controller/metal.rb:309:in `dispatch'
  from actionpack (7.1.3.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
  from actionpack (7.1.3.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:51:in `block in serve'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:124:in `each'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:124:in `find_routes'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (7.1.3.2) lib/action_dispatch/routing/route_set.rb:882:in `call'
  from railties (7.1.3.2) lib/rails/engine.rb:536:in `call'
  from railties (7.1.3.2) lib/rails/railtie.rb:226:in `public_send'
  from railties (7.1.3.2) lib/rails/railtie.rb:226:in `method_missing'
  from actionpack (7.1.3.2) lib/action_dispatch/routing/mapper.rb:22:in `block in <class:Constraints>'
  from actionpack (7.1.3.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:51:in `block in serve'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:124:in `each'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:124:in `find_routes'
  from actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (7.1.3.2) lib/action_dispatch/routing/route_set.rb:882:in `call'
  from flipper (1.3.0) lib/flipper/middleware/memoizer.rb:87:in `memoized_call'
  from flipper (1.3.0) lib/flipper/middleware/memoizer.rb:45:in `call'
  from rack-attack (6.7.0) lib/rack/attack.rb:127:in `call'
  from remotipart (5adbdb24ab89) lib/remotipart/middleware.rb:31:in `call'
  from warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
  from warden (1.2.9) lib/warden/manager.rb:34:in `catch'
  from warden (1.2.9) lib/warden/manager.rb:34:in `call'
  from rack (3.0.10) lib/rack/tempfile_reaper.rb:20:in `call'
  from rack (3.0.10) lib/rack/etag.rb:29:in `call'
  from rack (3.0.10) lib/rack/conditional_get.rb:31:in `call'
  from rack (3.0.10) lib/rack/head.rb:15:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
  from secure_headers (7a23cb6b350b) lib/secure_headers/middleware.rb:11:in `call'
  from rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
  from rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  from activesupport (7.1.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  from sentry-rails (5.17.3) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
  from sentry-ruby (5.17.3) lib/sentry/rack/capture_exceptions.rb:29:in `block (2 levels) in call'
  from sentry-ruby (5.17.3) lib/sentry/hub.rb:251:in `with_session_tracking'
  from sentry-ruby (5.17.3) lib/sentry-ruby.rb:403:in `with_session_tracking'
  from sentry-ruby (5.17.3) lib/sentry/rack/capture_exceptions.rb:20:in `block in call'
  from sentry-ruby (5.17.3) lib/sentry/hub.rb:59:in `with_scope'
  from sentry-ruby (5.17.3) lib/sentry-ruby.rb:383:in `with_scope'
  from sentry-ruby (5.17.3) lib/sentry/rack/capture_exceptions.rb:19:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from railties (7.1.3.2) lib/rails/rack/logger.rb:37:in `call_app'
  from railties (7.1.3.2) lib/rails/rack/logger.rb:24:in `block in call'
  from activesupport (7.1.3.2) lib/active_support/tagged_logging.rb:135:in `block in tagged'
  from activesupport (7.1.3.2) lib/active_support/tagged_logging.rb:39:in `tagged'
  from activesupport (7.1.3.2) lib/active_support/tagged_logging.rb:135:in `tagged'
  from railties (7.1.3.2) lib/rails/rack/logger.rb:24:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
  from config/middlewares/concerto_request_id.rb:37:in `block in call'
  from config/middlewares/concerto_request_id.rb:17:in `with'
  from config/middlewares/concerto_request_id.rb:36:in `call'
  from request_store (1.6.0) lib/request_store/middleware.rb:19:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/request_id.rb:28:in `call'
  from rack (3.0.10) lib/rack/method_override.rb:28:in `call'
  from rack (3.0.10) lib/rack/runtime.rb:24:in `call'
  from activesupport (7.1.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
  from rack (3.0.10) lib/rack/sendfile.rb:114:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/ssl.rb:79:in `call'
  from actionpack (7.1.3.2) lib/action_dispatch/middleware/assume_ssl.rb:21:in `call'
  from prometheus_exporter (66c1f39b72d8) lib/prometheus_exporter/middleware.rb:41:in `call'
  from railties (7.1.3.2) lib/rails/engine.rb:536:in `call'
  from autotuner (1.0.0) lib/autotuner/rack_plugin.rb:13:in `block in call'
  from autotuner (1.0.0) lib/autotuner/request_collector.rb:23:in `request'
  from autotuner (1.0.0) lib/autotuner/rack_plugin.rb:12:in `call'
  from puma (6.4.2) lib/puma/configuration.rb:272:in `call'
  from puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
  from puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
  from puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
  from puma (6.4.2) lib/puma/server.rb:464:in `process_client'
  from puma (6.4.2) lib/puma/server.rb:245:in `block in run'
  from puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

* it's the first time I got this error
* it doesn't happen in development or test environment
* it only happens in production or staging environment
* it happens since I've migrated the app to Ruby 3.3.1
* it happens very randomly
* it happens whatever urls you call
* restarting the Docker container (sometimes many times) solve the issue

I've made some patches to debug a bit further (see: https://github.com/trailblazer/trailblazer-activity/pull/61) and as expected I finally got :

```sh
#<Class:0x00007f7b89551408>:  (Trailblazer::Activity::Circuit::IllegalSignalError)
[31mUnrecognized Signal `Trailblazer::Activity::Right` returned from #<Proc:0x00007f7b88818f48 /app/vendor/bundle/ruby/3.3.0/bundler/gems/trailblazer-endpoint-827ac62bdb4c/lib/trailblazer/endpoint/options.rb:79 (lambda)>. Registered signals are, [0m
[32m[0m
```

But still, I really don't understand what's happening :/

**Comment by yogeshjain999** [comment]
We actually found similar issue when we were running `GC.compact` or `Process.warmup`. Avoiding it resolved the issue!

Are you calling it by any chance while starting the server or background processor ?

**Comment by n-rodriguez** [comment]
> We actually found similar issue when we were running `GC.compact` or `Process.warmup`. Avoiding it resolved the issue!

Yeah, I'm investigating this

> Are you calling it by any chance while starting the server or background processor ?

Yes, I explicitly added it to Puma config to see the impact on memory consumption.

What I don't understand is the random side of this issue : sometimes it works and sometimes not :/

**Comment by n-rodriguez** [comment]
> we found compaction garbage collects references of step methods that TRB stores in a hash as keys.

Yes, I found the same thing :/

**Comment by n-rodriguez** [comment]
I can reproduce it locally :

```sh
[2024-04-27T21:24:54.685747 #1641 #]  INFO [] - concerto.puma: Puma starting in cluster mode...
[2024-04-27T21:24:54.685793 #1641 #]  INFO [] - concerto.puma: * Puma version: 6.4.2 (ruby 3.3.1-p55) ("The Eagle of Durango")
[2024-04-27T21:24:54.685803 #1641 #]  INFO [] - concerto.puma: *  Min threads: 3
[2024-04-27T21:24:54.685810 #1641 #]  INFO [] - concerto.puma: *  Max threads: 3
[2024-04-27T21:24:54.685816 #1641 #]  INFO [] - concerto.puma: *  Environment: production
[2024-04-27T21:24:54.685826 #1641 #]  INFO [] - concerto.puma: *   Master PID: 1641
[2024-04-27T21:24:54.685834 #1641 #]  INFO [] - concerto.puma: *      Workers: 2
[2024-04-27T21:24:54.685848 #1641 #]  INFO [] - concerto.puma: *     Restarts: (✔) hot (✖) phased
[2024-04-27T21:24:54.685861 #1641 #]  INFO [] - concerto.puma: * Preloading application
[2024-04-27T21:24:54.686074 #1641 #]  INFO [] - concerto.puma: * Listening on http://0.0.0.0:5000
[2024-04-27T21:24:54.686133 #1641 #]  INFO [] - concerto.puma: Use Ctrl-C to stop
[2024-04-27T21:24:54.686899 #1641 #]  INFO [] - concerto.puma: * Starting control server on unix:///Users/nicolas/PROJECTS/CONCERTO/concerto/tmp/sockets/pumactl.sock
[2024-04-27T21:24:54.687080 #1641 #]  INFO [] - concerto.puma: * Finalizing master process (PID: 1641)
[#<Trailblazer::Activity::End semantic=:success>, [{"index"=>#<Class:0x000000012f5da6f8>, "show"=>#<Class:0x000000012e7e1ec0>, "our_team"=>#<Class:0x000000012c910dc0>}, nil]]
[2024-04-27T21:24:54.687282 #1641 #]  INFO [] - concerto.puma: ! Running nakayoshi GC (PID: 1641)
[2024-04-27T21:24:54.910039 #1641 #]  INFO [] - concerto.puma: ! Friendly fork preparation complete. (PID: 1641)
[2024-04-27T21:24:54.910178 #1641 #]  INFO [] - concerto.puma: WARNING hook before_fork failed with exception (Trailblazer::Activity::Circuit::IllegalSignalError) #<Class:0x000000012b597460>:
Unrecognized Signal `Trailblazer::Activity::Right` returned from #<Proc:0x000000012f737118 /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/ruby/3.3.0/bundler/gems/trailblazer-endpoint-0d58b7d09371/lib/trailblazer/endpoint/options.rb:79 (lambda)>. Registered signals are,
```

But it's still random :

```sh
[2024-04-27T21:24:41.376271 #1503 #]  INFO [] - concerto.puma: * Puma version: 6.4.2 (ruby 3.3.1-p55) ("The Eagle of Durango")
[2024-04-27T21:24:41.376282 #1503 #]  INFO [] - concerto.puma: *  Min threads: 3
[2024-04-27T21:24:41.376289 #1503 #]  INFO [] - concerto.puma: *  Max threads: 3
[2024-04-27T21:24:41.376296 #1503 #]  INFO [] - concerto.puma: *  Environment: production
[2024-04-27T21:24:41.376306 #1503 #]  INFO [] - concerto.puma: *   Master PID: 1503
[2024-04-27T21:24:41.376313 #1503 #]  INFO [] - concerto.puma: *      Workers: 2
[2024-04-27T21:24:41.376326 #1503 #]  INFO [] - concerto.puma: *     Restarts: (✔) hot (✖) phased
[2024-04-27T21:24:41.376337 #1503 #]  INFO [] - concerto.puma: * Preloading application
[2024-04-27T21:24:41.376554 #1503 #]  INFO [] - concerto.puma: * Listening on http://0.0.0.0:5000
[2024-04-27T21:24:41.376619 #1503 #]  INFO [] - concerto.puma: Use Ctrl-C to stop
[2024-04-27T21:24:41.377385 #1503 #]  INFO [] - concerto.puma: * Starting control server on unix:///Users/nicolas/PROJECTS/CONCERTO/concerto/tmp/sockets/pumactl.sock
[2024-04-27T21:24:41.377566 #1503 #]  INFO [] - concerto.puma: * Finalizing master process (PID: 1503)
[#<Trailblazer::Activity::End semantic=:success>, [{"index"=>#<Class:0x000000012f5a43a0>, "show"=>#<Class:0x000000012f1ed0e0>, "our_team"=>#<Class:0x000000012eda5960>}, nil]]
[2024-04-27T21:24:41.377788 #1503 #]  INFO [] - concerto.puma: ! Running nakayoshi GC (PID: 1503)
[2024-04-27T21:24:41.611192 #1503 #]  INFO [] - concerto.puma: ! Friendly fork preparation complete. (PID: 1503)
[#<Trailblazer::Activity::End semantic=:success>, [{"index"=>#<Class:0x000000012f5a43a0>, "show"=>#<Class:0x000000012f1ed0e0>, "our_team"=>#<Class:0x000000012eda5960>}, nil]]
```

**Comment by n-rodriguez** [comment]
To reproduce the bug :

In `config/puma.rb`:

```rb
  before_fork do
    PumaSettings.info '* Finalizing master process'

    #puts CampingsController.instance_variable_get('@normalizers')[:endpoints].call([]).inspect
    puts ConcertoFrance::PagesController.instance_variable_get('@normalizers')[:endpoints].call([]).inspect

    PumaSettings.warmup!

    #puts CampingsController.instance_variable_get('@normalizers')[:endpoints].call([]).inspect
    puts ConcertoFrance::PagesController.instance_variable_get('@normalizers')[:endpoints].call([]).inspect
```

**Comment by n-rodriguez** [comment]
Maybe `instance_variable_get` and `instance_variable_set` are a bit brittle and we should use Rails `class_attribute` or something like that, i don't know... @apotonick any idea?

**Comment by apotonick** [comment]
@n-rodriguez Where are we using `instance_variable_set` in `activity`? Isn't the problem more of a bug in Ruby where after compression the "ID" of a method changes? At least that's what I learned from a discussion with @yogeshjain999 and his work mate...?

**Comment by n-rodriguez** [comment]
> Where are we using `instance_variable_set` in `activity`?

Actually it's in `endpoint` gem (https://github.com/trailblazer/trailblazer-endpoint/blob/776cfbe9ce2fa133efce43d2c25335b6a4fa78a0/lib/trailblazer/endpoint/options.rb#L19) but I agree with you : it looks like a bug in Ruby,

**Comment by yogeshjain999** [comment]
I'm trying to reproduce this locally with puma but no luck. I want to reproduce it in a multi-threaded environment in order to identify and fix one (or more places) which GC garbage collects making objects null.

It is mentioned in [knowns issues](https://bugs.ruby-lang.org/issues/15626#Known-Issue) of GC.compact that usually marking objects in a "C extension" wrongly can cause such issues. But I don't see why such issue can occur in TRB and plain Ruby.

**Comment by n-rodriguez** [comment]
@yogeshjain999 are you using Puma `single-mode` or `cluster-mode`? 

> It is mentioned in [knowns issues](https://bugs.ruby-lang.org/issues/15626#Known-Issue) of GC.compact that usually marking objects in a "C extension" wrongly can cause such issues. But I don't see why such issue can occur in TRB and plain Ruby.

+1

**Comment by yogeshjain999** [comment]
@n-rodriguez in cluster-mode.

**Comment by rmzoni** [comment]
Hey @n-rodriguez @yogeshjain999 , did you guys made any progress about this issue?

We are having the same issue running trailblazer in rails 7.2 and sidekiq 7.3.

**Comment by n-rodriguez** [comment]
@rmzoni what ruby version are you running? it's fixed with version 3.3.5.

**Comment by apotonick** [comment]
Oh cool, I didn't know this is fixed in Ruby, but it makes sense, as there shouldn't be restrictions on what you use as a hash key. :sparkles: Thanks! @tiagotex did you know that?

**Comment by rmzoni** [comment]
Hi I'm using ruby 3.3.5 and the problem only happens on sidekiq.

In the rails puma servee.the problem seems to not occurs.

**Comment by n-rodriguez** [comment]
> Hi I'm using ruby 3.3.5 and the problem only happens on sidekiq.

Weird... I'm using Sidekiq too and doesn't have this issue. It even worked with Ruby < 3.3.5 (only Puma had this bug with Ruby < 3.3.5)

**Comment by rmzoni** [comment]
> > Hi I'm using ruby 3.3.5 and the problem only happens on sidekiq.
> 
> Weird... I'm using Sidekiq too and doesn't have this issue. It even worked with Ruby < 3.3.5 (only Puma had this bug with Ruby < 3.3.5)

Could you provide your sidekiq version, rails version, Sidekiq config and rails config?

**Comment by n-rodriguez** [comment]
> Could you provide your sidekiq version, rails version

ruby 3.3.5
rails 7.2.1
sidekiq 7.3.2
puma 6.4.3

> Sidekiq config and rails config?

what do you want exactly?

**Comment by rmzoni** [comment]
> what do you want exactly?
This information help a lot for doing some tests.

But I´m looking for more specific configurations like: are you using eager load on rails? What are the the configuration server sidekiq initializer are you using.

**Comment by n-rodriguez** [comment]
> are you using eager load on rails?

Eager load is by default in production environment.

**Comment by n-rodriguez** [comment]
@tiagotex good catch 👍  I thought it was fixed in Ruby 3.3.5 because before the app failed to start and succeed with 3.3.5.

**Comment by n-rodriguez** [comment]
If I run your script with `Process.warmup` instead of `GC.verify_compaction_references(expand_heap: true, toward: :empty)` I've got a different result :

`GC.verify_compaction_references(expand_heap: true, toward: :empty)`: 

```sh
"data"
"data"
"data"
60
60
80
1363190962308822659
1363190962308822659
1363190962308822659
nil # <- nil data
nil # <- nil data
nil # <- nil data
60
60
100
-268338980614592820
-268338980614592820
-268338980614592820
"data"
"data"
nil
60
60
120
-268338980614592820
-268338980614592820
-268338980614592820
```
`Process.warmup`:

```sh
"data"
"data"
"data"
60
60
80
-2346256075726202682
-2346256075726202682
-2346256075726202682
"data" # <- data
"data" # <- data
"data" # <- data
60
60
100
-2346256075726202682
-2346256075726202682
-2346256075726202682
"data"
"data"
nil
60
60
120
-2346256075726202682
-2346256075726202682
-2346256075726202682
```

**Comment by apotonick** [comment]
We added the patch provided by @tiagotex in 0.16.3. https://github.com/trailblazer/trailblazer-activity/commit/0511f24c041f19c241e2a72b63600dc3e0f8d2cb

**Comment by n-rodriguez** [comment]
@tiagotex  Thank you!

**Comment by n-rodriguez** [comment]
@tiagotex linked issue? https://redmine.ruby-lang.org/issues/20853

**Comment by apotonick** [comment]
@rmzoni I was wondering, did `trailblazer-activity-0.16.3` solve that issue for you, too?

**Comment by apotonick** [comment]
> @tiagotex linked issue? https://redmine.ruby-lang.org/issues/20853

@n-rodriguez Thanks for this link, that's exactly the issue we are facing. So apparently, we can revert this fix as it's fixed in Ruby itself?

**Comment by rmzoni** [comment]
> @rmzoni I was wondering, did `trailblazer-activity-0.16.3` solve that issue for you, too?

We update a few weeks ago and the problem seems to not happen anymore.

**Comment by n-rodriguez** [comment]
@apotonick 

 > So apparently, we can revert this fix as it's fixed in Ruby itself?

I guess we can 👍 On the other hand we can keep the test to avoid regressions.

**Comment by apotonick** [comment]
Here's a small blog post about this https://dev.to/trailblazer/gc-compaction-behold-your-hash-keys-2ii1
